# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HypsometricCurve
                                 A QGIS plugin
 Calculate and draw the hypsometric curve of a drainage basin starting from a vector layer of contour lines and a vector layer that delimits the basin itself.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-17
        copyright            : (C) 2024 by Dr. Geol. Faustino Cetraro
        email                : geol-faustino@libero.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HypsometricCurve class from file HypsometricCurve.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hypsometric_curve import HypsometricCurve
    return HypsometricCurve(iface)
